apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nas-grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-nas
  resources:
    requests:
      storage: 10Gi